trigger: 
- main

resources:
  repositories:
    - repository: powerbi-visuals-utils-localizationutils
      endpoint: 'pbicvloc GitHub'
      type: github
      name: microsoft/powerbi-visuals-utils-localizationutils
      ref: refs/heads/main

stages:
- stage: build
  jobs:
  - job: main
    pool:
      vmImage: 'windows-latest'

    steps:
      - checkout: powerbi-visuals-utils-localizationutils
        persistCredentials: true
      - powershell: |
          $branchName = "parsed_localizations_" + (Get-Date -Format "yyyy-MM-dd_HH-mm-ss")
          Write-Host "##vso[task.setvariable variable=branchName]$branchName"
        name: SetVariables
        displayName: 'Set Variables'
      - task: NodeTool@0
        inputs:
          versionSpec: '18.x'
        displayName: 'Install Node.js'
      - script: |
          git config --global user.name "$(LOC_BOT_NAME)"
          git config --global user.email "$(LOC_BOT_EMAIL)"
          git config --global core.autocrlf false
          git checkout -b $(branchName)
        displayName: 'Configure Git'
      - task: OneLocBuild@2
        env:
          SYSTEM_ACCESSTOKEN: $(System.AccessToken)
        inputs:
          locProj: 'LocProject.json'
          outDir: '$(Build.SourcesDirectory)'
          isCreatePrSelected: true
          repoType: 'gitHub'
          prSourceBranchPrefix: 'locfiles'
          dependencyPackageSource: 'https://powerbi.pkgs.visualstudio.com/PowerBIClients/_packaging/VisualsMonitorFeed/nuget/v3/index.json'
          packageSourceAuth: 'patAuth'
        displayName: 'Run OneLocBuild'
      - script: |
          ls -la
          echo "Installing dependencies..."
          npm install
          
          echo "Running parseNewLocalizations..."
          npm run parseNewLocalizations --verbose
          
          echo "Git status:"
          git status --short
    
          if git diff-index --quiet HEAD --; then
            echo "No changes to commit"
            exit 0
          else
            echo "Changes detected, proceeding with commit"
            git add localizations/*
            git commit -m "Update localizations"
            git push origin $(branchName)
          fi
        displayName: 'Process and Push Localizations'
        continueOnError: true
      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: '$(Build.SourcesDirectory)'
          artifact: 'drop'
          publishLocation: 'pipeline'
        displayName: 'Publish Pipeline Artifact'
