trigger: 
- main

resources:
  repositories:
    - repository: powerbi-visuals-utils-localizationutils
      endpoint: 'pbicvloc GitHub'
      type: github
      name: microsoft/powerbi-visuals-utils-localizationutils
      ref: refs/heads/main
    - repository: tools
      type: git
      name: MWC/administrative-tools
      ref: refs/heads/master

stages:
- stage: build
  jobs:
  - job: main
    pool:
      name: PowerbiClients-Managed-Pool
      type: windows  # read more about custom job pool types at https://aka.ms/obpipelines/yaml/jobs

    steps:
      - checkout: self
        persistCredentials: true
      - template: "BuildTemplates/managedIdentityToken.yml@tools"
      - checkout: powerbi-visuals-utils-localizationutils
      - task: OneLocBuild@2
        env:
          SYSTEM_ACCESSTOKEN: $(MIToken)
        inputs:
          locProj: 'LocProject.json'
          outDir: '$(Build.ArtifactStagingDirectory)'
          isCreatePrSelected: true
          repoType: 'gitHub'
          prSourceBranchPrefix: 'locfiles'
          dependencyPackageSource: 'https://powerbi.pkgs.visualstudio.com/PowerBIClients/_packaging/VisualsMonitorFeed/nuget/v3/index.json'
          packageSourceAuth: 'patAuth'
      - task: PublishPipelineArtifact@1
        displayName: 'Publish Pipeline Artifact'
        inputs:
            targetPath: '$(Build.ArtifactStagingDirectory)'
            artifact: drop